### ISSUE TITLE
Secret store CSI driver AKV Provider is failing on GPU nodes

### ISSUE THREAD

**Issue by nilekhc** [Azure/AgentBaker#945]
AKV Provider is failing to start due to permission issue on GPU nodes with error:
`Error: failed to create containerd task: OCI runtime create failed: container_linux.go:344: starting container process caused "chdir to cwd (\"/home/nonroot\") set in config.json failed: permission denied": unknown`

We deploy with following security context:
```
securityContext:
  runAsUser: 0
  capabilities:
    drop:
    - ALL
```
